# Write a playbook to install httpd package in all host nodes & start it
- hosts: all
  become: true
  tasks:
    - name: install httpd package
      yum:
        name: httpd
        state: present
    - name: copy index.html
      copy:
      src: index.html
      dest: /var/www/html/index.html
    - name: re-start server  
      service:
        name: httpd
        state: started
...